// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqqxlafwywvqasxsailj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcXhsYWZ3eXd2cWFzeHNhaWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTUwNjEsImV4cCI6MjA2MTczMTA2MX0.tHZKdHBkpdBJaMdqPipsKCLs8dX1H-JO5Dfr_Bi1oks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);